### ISSUE TITLE
Wavelet was unable to instantiate PresetReverb effects & Virtualizer effects issue

### ISSUE THREAD

**Issue by snowstorm-trail** [Pittvandewitt/Wavelet#231]
![Screenshot_20230224_035215_Wavelet](https://user-images.githubusercontent.com/126207769/221045959-c40909cd-a45f-4db9-bad5-1bd29b4631fb.jpg)
It is officially purchased version of Wavelet from Google Play Store and when played music from Apple Music android such error occurs in Wavelet app. Please tell me a method to troubleshoot or may the issue be fixed.

**Comment by snowstorm-trail** [comment]
@Pittvandewitt The error message is Wavelet was unable to instantiate Insert Preset Re...

**Comment by snowstorm-trail** [comment]
@Pittvandewitt I noticed that it does audio processing for Qobuz Beta app when played music from it.

**Comment by bushcoffee** [comment]
Same issue here.
Pixel 6 Pro. Android 13 - 5th Feb 2023 security update.
App purchased from Play Store. 
If I enable Legacy Mode in the app, it seems to work. I can then go and select my headphones and the EQ is set. 
With Legacy Mode disabled, I just have the shrug emoji and the instantiate error.
![Screenshot_20230316-102749](https://user-images.githubusercontent.com/71377415/225494364-f12663b1-2a85-4ebb-a214-ee8c3a96a8fd.png)
![Screenshot_20230316-102736](https://user-images.githubusercontent.com/71377415/225494375-e19a2729-f925-4347-b6e4-21180c326682.png)

**Comment by greenza** [comment]
I also updated my pixel 7 and got the same error, I tried reinstalling the app but it **didn't** fix it.

**Comment by Pittvandewitt** [comment]
This happens if an old session from any music player is not removed from the cache in Wavelet. The cache is cleared after a reboot, which should fix the issue. Make sure Wavelet is allowed to start at boot: https://dontkillmyapp.com/ (search for auto start options for your device)

**Comment by Splunger** [comment]
This issue definitely still exists.. Have rebooted, cleared cache, followed all the sound quality and battery optimization tops, etc. It "works" with legacy mode enabled, but the bass is extremely distorted. Clicking disable legacy immediately results in the unable to... Message.

This issue has existed for a long time for me across 3 different types of earbuds or headphones.

**Comment by WhitespaceQ** [comment]
![WhatsApp Image 2023-08-23 at 11 50 21](https://github.com/Pittvandewitt/Wavelet/assets/68904781/211daaf4-578d-4d6a-ba13-a3e1a874d0f8)

I also randomly got this message, there is nothing changed on the phone.
